Adiciona Rust aos exercicios do Mundo 1
Coding-in-community/exercicios-CeV pull request #66
Opened 2022-08-04 21:56 UTC by BearingMe

2022-08-06 02:04 UTC, matheusfelipeog reviewed
@BearingMe você poderia adicionar o bradge do Rust no arquivo [README.md](https://github.com/Coding-in-community/exercicios-CeV/blob/master/README.md) na seção "Linguagens utilizadas atualmente" da mesma forma que os das outras linguagens?

E também adicionar uma coluna para Rust e um link para cada um dos exercícios feitos na [tabela de indexação](https://github.com/Coding-in-community/exercicios-CeV/tree/master/exs/mundo_1), conforme o padrão da tabela?

Essas adições fazem parte do contexto do PR, então é interessante agrupa-las aqui

2022-08-08 23:11 UTC, BearingMe commented
Foi adicionado Rust a lista de exercicios do mundo 1. Em relação a outros mundos, será adicionado durante o periodo de revisão ao termino da resolução dos exercicios (atualmente no 063).

2022-08-13 19:26 UTC, matheusfelipeog requested changes
Obrigado por adicionar os links dos exercícios de Rust à tabela @BearingMe.

Revisei todos os exercícios e estão corretos, com exceção dos dois que estão comentados abaixo. Assim que forem corrigidos o PR poderá ser mesclado.

2022-08-13 19:26 UTC, matheusfelipeog commented on exs/mundo_1/rust/033.rs
> +    let mut maior = num2;
Na lógica atual, o primeiro valor informado nunca será classificado como maior, visto que não há nenhuma verificação/atribuição para ele.

Para funcionar corretamente, pode-se assumir que o primeiro valor já é o maior:
```suggestion
    let mut maior = num1;
```

2022-08-13 19:26 UTC, matheusfelipeog commented on exs/mundo_1/rust/023.rs
> +    println!("Número inválido");
Sempre será impresso no terminal a string "Número Inválido", independente se o número é ou não válido.

Uma das possíveis soluções é adicionar essa instrução dentro do escopo de um `else` da condição anterior:

```suggestion
    } else {
        println!("Número inválido");
    }
```

2022-08-15 05:19 UTC, matheusfelipeog approved these changes
Obrigado pelas correções, agora está tudo certo ;)

2022-08-15 05:22 UTC, merged